### ISSUE TITLE
MailClient.sendMail blocks vert.x event loop

### ISSUE THREAD

**Issue by sfitts** [vert-x3/vertx-mail-client#53] opened 2016-01-20 20:42 UTC
I happened to be running on a flaky network today (thank you Comcast) and noticed that the host lookup is issuing a blocking call directly on the vertx event loop.  Here is the stack trace from the blocked thread checker:

```
Jan 20, 2016 12:15:50 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-10,5,main] has been blocked for 20120 ms, time limit is 2000
io.vertx.core.VertxException: Thread blocked
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at java.net.InetAddress.getByName(InetAddress.java:1076)
	at java.net.InetSocketAddress.<init>(InetSocketAddress.java:220)
	at io.vertx.core.net.impl.NetClientImpl.connect(NetClientImpl.java:180)
	at io.vertx.core.net.impl.NetClientImpl.connect(NetClientImpl.java:97)
	at io.vertx.ext.mail.impl.SMTPConnection.openConnection(SMTPConnection.java:176)
	at io.vertx.ext.mail.impl.SMTPStarter.start(SMTPStarter.java:50)
	at io.vertx.ext.mail.impl.SMTPConnectionPool.createConnection(SMTPConnectionPool.java:234)
	at io.vertx.ext.mail.impl.SMTPConnectionPool.createNewConnection(SMTPConnectionPool.java:218)
	at io.vertx.ext.mail.impl.SMTPConnectionPool.getConnection0(SMTPConnectionPool.java:142)
	at io.vertx.ext.mail.impl.SMTPConnectionPool.getConnection(SMTPConnectionPool.java:72)
	at io.vertx.ext.mail.impl.MailClientImpl.sendMail(MailClientImpl.java:68)
	at io.vertx.ext.mail.MailClient$sendMail$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
```

Looks like the underlying issue may be related to NetClient, but one way or another it would seem that this shouldn't block.

As a workaround I'm going to run this under a "executeBlocking" handler.

**Comment by cescoffier** [comment] 2016-01-21 06:29
I guess it has been fixed in master. The issue is that IP lookup is blocking.

**Comment by sfitts** [comment] 2016-01-21 15:21
@cescoffier thanks.  Do you know if this will be in the 3.2.1 release the @vietj mentioned was targeted for the end of the month or is this 3.3?

**Comment by cescoffier** [comment] 2016-01-22 06:15
Hello @sfitts, the 3.2.1 should be released end of January / beginning of February. 3.3.0 should land in Q2 2016.

**Comment by sfitts** [comment] 2016-01-22 06:31
@cescoffier thanks for the info.  Do you know which release this fix will be in?

**Comment by cescoffier** [comment] 2016-01-22 06:33
@sfitts I hope so.
@alexlehm could you confirm ?

**Comment by alexlehm** [comment] 2016-02-01 12:07
@cescoffier sorry, I missed the question, I believe the hostname resolution is now done with execute blocking in all cases, so the option is not necessary

**Comment by alexlehm** [comment] 2016-02-01 12:19
@cescoffier @sfitts does it make sense for this to be configurable or would it be better to use blocking dns resolution all the time?
I cannot think of a usecase where it makes sense to not do that. I assume the dns lookup will be changed in the core vertx at some point, so that all dns lookups will be async and we could just take out the specific code in the module.

**Comment by cescoffier** [comment] 2016-02-01 12:34
My fix does not fix this case, but when you try connecting to a SMTP server where name resolution may be slow. This would later be fixed in vert.x core with the new netty, but for now we need to fix it here.

The option is just there for compatibility purpose, as before it was doing a blocking resolution. But having an option is debatable (@vietj ?).

**Comment by sfitts** [comment] 2016-02-01 15:15
I'm not a huge fan of the option, since it's not like the user's code has any control over whether or not the call will take too long to run (I only discovered it by accident due to a intermittant network outage).  Seems like the code should just assume it might block and always run it that way.

**Comment by cescoffier** [comment] 2016-02-01 15:19
Ok, I will get rid of the option, but this may change the behavior.

**Comment by cescoffier** [comment] 2016-02-01 15:26
Option removed.

**Comment by alexlehm** [comment] 2016-02-02 00:15
Have to take a closer look how this plays together with ssl connections, on first glance it looks ok

**Comment by cescoffier** [comment] 2016-02-02 09:43
The fix does not play with SSL. It just create an `InetAddress` (which does not involve SSL at all), retrieve the resolved IP and pass this IP instead of the host name (as it's already resolved). SSL comes into the game during the `connect` method as before.

**Comment by vietj** [comment] 2016-02-02 10:21
looks good to me.

**Closed** 2016-02-02 13:24 UTC
